### ISSUE TITLE
Backport mini-AOD-2018 to mini-AOD-2017

### ISSUE THREAD

**Issue by khaosmos93** [cms-analysis/SUSYBSMAnalysis-Zprime2muAnalysis#68]
We need to converge on below topics before backporting recent updates in mini-AOD-2018 branch to mini-AOD-2017 branch

1. All the c++ core parts seem trivial to be backported

2. Era dependent python config files which need to be slightly modified/updated:
- python/goodlumis.py
- python/MCSamples.py
- python/hltTriggerMatch_cfi.py
- python/MCFilters_cfi.py
- cmsRun configs, e.g. histos.py

please add any missing files

3. python/OurSelection2017_cff.py and python/OurSelection2018_cff.py should be identical
Do we want to keep both?

4. As we do not have "expectedNnumberOfMatchedStations" in 94X releases, it would be easier to run everything on 102X
Is there any reason why we should not?

**Comment by cschnaible** [comment]
4. "Is there any reason why we should not?"
I don't think we can run 94X data and MC in a 102X release and expect everything to work as expected... I think we would be better off to re-implement this function in the Zprime2muLeptonProducer and store the result as a userFloat. It doesn't look like it is too crazy:
https://github.com/cms-sw/cmssw/blob/master/DataFormats/MuonReco/src/Muon.cc#L136-L153 

This then answers question 3. Do we want to keep both? I think yes, we would because we would select on this matched muon station requirement in the Zprime2muCompositeCandidatePicker instead of the Zprime2muCombiner.

**Comment by JanFSchulte** [comment]
My two cents on this: There should be no reason not to run all 3 years in 102X. 
In our analysis we are doing exactly 0 things that rely on CMSSW functionality for anything else than event selection, the muon quantities are fixed in the mini-AODs and we never change them. It would make our lives quite a bit easier to not have to maintain to branches to execute exactly the same code.

**Comment by BenjaminRS** [comment]
I know of this [summary page](https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmVAnalysisSummaryTable) from PdmV. However, asking Sam he said that it is fine to run 94X/2017 data us 102X

**Comment by khaosmos93** [comment]
Hi all,
Thanks a lot for the comments!
I agree that we can run everything on 102X. But it would be better to keep separate branches for 2017 and 2018 for the record, as some of the config files should be different.

Concerning the selection config files, I think we can keep both files, OurSelection2017_cff.py and OurSelection2018_cff.py, with identical contents or just keep only one with changed name, e.g. OurSelection2017and2018_cff.py. I don't have strong opinion on this.

**Comment by BenjaminRS** [comment]
Isn't having OurSelection2017_cff.py in the 2017 branch and OurSelection2018_cff.py in the 2018 branch possible? I would prefer that if there are other configurations which are dependant on the year (to stop the wrong config running for a certain year).

**Comment by cschnaible** [comment]
>  But it would be better to keep separate branches for 2017 and 2018 for the record, as some of the config files should be different.

I agree with keeping 2017 and 2018 separate. From the PdmV summary page 2016 and 2017 I see that can both be done in 94X now so we could at least we get some reduction in branches.

>  I think we can keep both files ... with identical contents or just keep only one with changed name

I propose condensing them into one file and calling it OurSelectionRun2Legacy.py. 

Edit: I just realized I proposed conflicting ideas to keep the 2017 and 2018 branches separate but condense the 2017 and 2018 OurSelection python config files because of the expectedNnumberOfStations method. I second Benjamin's proposal regarding the config file names & branches.
